### ISSUE TITLE
Stargate Coin send Transaction Error

### ISSUE THREAD

**Issue by arnabghose997** [cosmos/cosmjs#1006]
I am trying to send tokens between accounts on a blockchain scaffolded by `starport`. Following is my code:

```js
const { DirectSecp256k1HdWallet } = require("@cosmjs/proto-signing");
const { assertIsBroadcastTxSuccess, SigningStargateClient, StargateClient } = require("@cosmjs/stargate");

const sendCoins = async () => {
  const mnemonic = "some mnemonic";
  const wallet = await DirectSecp256k1HdWallet.fromMnemonic(mnemonic);
  const [firstAccount] = await wallet.getAccounts();

  const rpcEndpoint = "http://localhost:26657"; // Tendermint RPC endpoint
  const client = await SigningStargateClient.connectWithSigner(rpcEndpoint, wallet);

  const recipient = "cosmos137x..";
  const amount = {
    denom: "uatom",
    amount: "10",
  };
  const result = await client.sendTokens(firstAccount.address, recipient, [amount], "Have fun with your star coins");
  assertIsBroadcastTxSuccess(result);
};

sendCoins();
```
While executing the above code, I am getting the following error:
```
~/code/research/Network/devnet/work/wallet/node_modules/@cosmjs/math/build/integers.js:95
        if (!str.match(/^-?[0-9]+$/)) {
                 ^

TypeError: Cannot read properties of undefined (reading 'match')
    at Function.fromString (/home/arnab/code/research/Network/devnet/work/wallet/node_modules/@cosmjs/math/build/integers.js:95:18)
    at SigningStargateClient.signDirect (/home/arnab/code/research/Network/devnet/work/wallet/node_modules/@cosmjs/stargate/build/signingstargateclient.js:253:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SigningStargateClient.signAndBroadcast (/home/arnab/code/research/Network/devnet/work/wallet/node_modules/@cosmjs/stargate/build/signingstargateclient.js:177:23)
    at async sendCoins (/home/arnab/code/research/Network/devnet/work/wallet/token_transaction.js:17:18)
arnab@arnab-PC:~/code/research/Network/devnet/work/wallet$ 
```

**Comment by webmaster128** [comment]
Is the z in Stargaze in the title a typo?

`sendTokens` needs to get a fee argument between the amount and the memo.

**Comment by webmaster128** [comment]
Better adapt your code. 0.24 is old and unmaintained.

> While sending atoms from one account to another, why is the gas token set to "ucosm"? And can it be be changed "ucosm" to "uatom"?

The fee token depends on the chain you connect to. The local test chains in our repo use ucosm. uatom is used on the Cosmos Hub. I don't know which tokens Starport configures.

**Comment by webmaster128** [comment]
> sendTokens needs to get a fee argument between the amount and the memo.

**Comment by arnabghose997** [comment]
I added the fee param and it worked, for the Stargate version 0.27

Following is the code I now used:

```js
const { DirectSecp256k1HdWallet } = require("@cosmjs/proto-signing");
const { SigningStargateClient, StargateClient } = require("@cosmjs/stargate");

const sendCoins = async () => {
  const mnemonic = "some mnemonic";
  const wallet = await DirectSecp256k1HdWallet.fromMnemonic(mnemonic);
  const [firstAccount] = await wallet.getAccounts();

  const rpcEndpoint = "http://localhost:26657";
  const client = await SigningStargateClient.connectWithSigner(rpcEndpoint, wallet);

  const recipient = "cosmos1zd6...";
  const amount = [{
    denom: "uatom",
    amount: "223",
  }];

  const fee = {
    amount: [
        {
        denom: "uatom", 
        amount: "10",
        },
    ],
    gas: "62000",
  };

  const result = await client.sendTokens(firstAccount.address, recipient, amount, fee,"Have fun with your star coins");
  console.log(result)
};

sendCoins();
```

Thank you @webmaster128 for your help.

**Comment by webmaster128** [comment]
Glad to hear it works!
