### ISSUE TITLE
query ValidatorDelegations info shows 502 bad gateway error

### ISSUE THREAD

**Issue by shellhue** [cosmos/cosmjs#1049]
I am learning cosmjs following [tutorial](https://github.com/cosmos/cosmjs/blob/main/packages/stargate/CUSTOM_PROTOBUF_CODECS.md). I try to query the staking module of cosmos hub. All query methods succeed except `ValidatorDelegations`. when querying `ValidatorDelegations`, it responds with error `status: 502, statusText: 'Bad Gateway'`. i have debugged for a week. still stuck in it. Anyone has any idea?

the code is below:
```typescript
import { createProtobufRpcClient, QueryClient } from "@cosmjs/stargate";
import { Tendermint34Client } from "@cosmjs/tendermint-rpc";
import Long from "long";
import { QueryClientImpl as BankQueryClientImpl } from "./codec/cosmos/bank/v1beta1/query";
import { QueryClientImpl as StakingQueryClientImpl } from "./codec/cosmos/staking/v1beta1/query";

async function main() {
  const tendermintClient = await Tendermint34Client.connect("https://rpc.cosmos.network:443/");
  const queryClient = new QueryClient(tendermintClient);
  const rpcClient = createProtobufRpcClient(queryClient);
  const address = "cosmos1y535snpnn772hw0jw6v3snkhdme4mkz66pw59k"
  const validatorAddr = "cosmosvaloper10e4vsut6suau8tk9m6dnrm0slgd6npe3jx5xpv";
  
  const bankQueryService = new BankQueryClientImpl(rpcClient);
  const stakingQueryService = new StakingQueryClientImpl(rpcClient);

  // query
  console.log("============delagatorInfo============");
  const delagatorInfo = await stakingQueryService.Delegation({
    validatorAddr: validatorAddr,
    delegatorAddr: address,
  });
  console.log(delagatorInfo);

  // query
  console.log("============delegatorInfos============");
  const delegatorInfos = await stakingQueryService.DelegatorDelegations({
    delegatorAddr: address,
  });
  console.log(delegatorInfos)

  // query
  console.log("============delegators============");
  const delegators = await stakingQueryService.ValidatorDelegations({
    validatorAddr: validatorAddr,
  })
  console.log(delegators)

  return "succeed."
}

main().then(res => {
  console.log("res:", res)
}).catch(err => {
  console.log("err:", err)
});
```

Running enviroment:
```
macos 10.15.7
node v16.14.0
npm v8.3.1
```

dependent pacakges:
```
"devDependencies": {
    "@typescript-eslint/eslint-plugin": "^5.12.0",
    "@typescript-eslint/parser": "^5.12.0",
    "eslint": "^8.9.0",
    "ts-proto": "^1.105.1",
    "typescript": "^4.5.5"
  },
  "dependencies": {
    "@cosmjs/proto-signing": "^0.27.1",
    "@cosmjs/stargate": "^0.27.1",
    "@cosmjs/tendermint-rpc": "^0.27.1"
  }
```

Ouput:
```

============delagatorInfo============
{
  delegationResponse: {
    delegation: {
      delegatorAddress: 'cosmos1y535snpnn772hw0jw6v3snkhdme4mkz66pw59k',
      validatorAddress: 'cosmosvaloper10e4vsut6suau8tk9m6dnrm0slgd6npe3jx5xpv',
      shares: '10100000000000000000000000'
    },
    balance: { denom: 'uatom', amount: '10100000' }
  }
}
============delegatorInfos============
{
  delegationResponses: [ { delegation: [Object], balance: [Object] } ],
  pagination: {
    nextKey: Uint8Array(0) [],
    total: Long { low: 1, high: 0, unsigned: true }
  }
}
============delegators============
err: Error: Request failed with status code 502
    at createError (/Users/huangzeyu/blockchain/vuetest/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/huangzeyu/blockchain/vuetest/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/huangzeyu/blockchain/vuetest/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (node:events:532:35)
    at endReadableNT (node:internal/streams/readable:1346:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  config: {
    url: 'https://rpc.cosmos.network:443/',
    method: 'post',
    data: '{"jsonrpc":"2.0","id":118513517799,"method":"abci_query","params":{"path":"/cosmos.staking.v1beta1.Query/ValidatorDelegations","data":"0a34636f736d6f7376616c6f7065723130653476737574367375617538746b396d36646e726d30736c6764366e7065336a7835787076","prove":false}}',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/0.21.4',
      'Content-Length': 260
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    }
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: null,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'rpc.cosmos.network',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'rpc.cosmos.network',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 148,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'POST / HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/json\r\n' +
      'User-Agent: axios/0.21.4\r\n' +
      'Content-Length: 260\r\n' +
      'Host: rpc.cosmos.network\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 502,
      statusMessage: 'Bad Gateway',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://rpc.cosmos.network:443/',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 8,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'rpc.cosmos.network',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 260,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://rpc.cosmos.network:443/',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      'user-agent': [Array],
      'content-length': [Array],
      host: [Array]
    }
  },
  response: {
    status: 502,
    statusText: 'Bad Gateway',
    headers: {
      date: 'Sun, 20 Feb 2022 11:55:06 GMT',
      'content-length': '11',
      'content-type': 'text/plain; charset=utf-8',
      connection: 'close'
    },
    config: {
      url: 'https://rpc.cosmos.network:443/',
      method: 'post',
      data: '{"jsonrpc":"2.0","id":118513517799,"method":"abci_query","params":{"path":"/cosmos.staking.v1beta1.Query/ValidatorDelegations","data":"0a34636f736d6f7376616c6f7065723130653476737574367375617538746b396d36646e726d30736c6764366e7065336a7835787076","prove":false}}',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      transitional: [Object]
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'POST / HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: axios/0.21.4\r\n' +
        'Content-Length: 260\r\n' +
        'Host: rpc.cosmos.network\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'rpc.cosmos.network',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: 'Bad Gateway'
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
```

the code is here:
[code.zip](https://github.com/cosmos/cosmjs/files/8103919/code.zip)

**Comment by webmaster128** [comment]
Did you try tris with different nodes? Ideally our own nodes.  rpc.cosmos.network is a popular endpoint under high load. Maybe the reponse is just too big and the proxy server refuses to serve it.

**Comment by shellhue** [comment]
Thanks for your reply. The rpc endpoint I am using is "https://rpc.cosmos.network:443/", which is exact the one you recommend.

**Comment by JGJP** [comment]
What's the verdict on this? I'm dealing with the same issue, except it works when using REST instead of RPC

**Comment by webmaster128** [comment]
HTTP 5xx is a server error. Please contact the providers of those endpoints. Closing as there is nothing the library can do about it.
