### ISSUE TITLE
Error while decoding validator updates due to slashing

### ISSUE THREAD

**Issue by blorgon1** [cosmos/cosmjs#1177]
As seen in the [results for Cosmos block 10883046](https://rpc.cosmos.network/block_results?height=10883046), when a validator is slashed the `validator_updates` entry does not have a `power` attribute. The decoder for this should be changed to make this property optional, as it is currently required and cannot be parsed.

Full error:
```
Error: Value must not be undefined
    at assertSet (.../node_modules/@cosmjs/tendermint-rpc/build/tendermint34/encodings.js:13:15)
    at assertNotEmpty (.../node_modules/@cosmjs/tendermint-rpc/build/tendermint34/encodings.js:107:5)
    at decodeValidatorUpdate (.../node_modules/@cosmjs/tendermint-rpc/build/tendermint34/adaptor/responses.js:122:79)
    at Array.map (<anonymous>)
    at decodeBlockResults (.../node_modules/@cosmjs/tendermint-rpc/build/tendermint34/adaptor/responses.js:130:58)
    at decodeBlockResults (.../node_modules/@cosmjs/tendermint-rpc/build/tendermint34/adaptor/responses.js:384:16)
    at Tendermint34Client.doCall (.../node_modules/@cosmjs/tendermint-rpc/build/tendermint34/tendermint34client.js:306:16)
```

Related to #1142.

**Comment by y-pakorn** [comment]
Good catch! Tendermint proto also not stated this field as non-nullable.
https://github.com/tendermint/tendermint/blob/master/proto/tendermint/abci/types.proto#L421

**Comment by webmaster128** [comment]
There is this data dump from protobuf generated Go code with omitempty: https://github.com/tendermint/tendermint/blob/v0.35.6/abci/types/types.pb.go#L2656

**Comment by webmaster128** [comment]
This was backported to 0.28 in https://github.com/cosmos/cosmjs/pull/1185 and released as part of 0.28.8.

**Comment by webmaster128** [comment]
Indeed. The entire commit https://github.com/cosmos/cosmjs/commit/5ec2da12c4798b44cfbab963b39db9858dda944b uses the wrong version everywhere. Big fail. Will release 0.28.9 now to clean up the mess.

**Comment by webmaster128** [comment]
0.28.9 is out
