### ISSUE TITLE
this.registry.encode is not a function

### ISSUE THREAD

**Issue by sajshuai** [cosmos/cosmjs#1267]
TypeError: this.registry.encode is not a function
    at SigningStargateClient.signDirect (/Users/suanjie/Documents/Projects/NodeJS/Cosmos/atom_cosmjs/node_modules/_@cosmjs_stargate@0.28.13@@cosmjs/stargate/build/signingstargateclient.js:242:43)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SigningStargateClient.signAndBroadcast (/Users/suanjie/Documents/Projects/NodeJS/Cosmos/atom_cosmjs/node_modules/_@cosmjs_stargate@0.28.13@@cosmjs/stargate/build/signingstargateclient.js:167:23)

**Comment by webmaster128** [comment]
What did you try to do there? Did you create an instance of SigningStargateClient?

**Comment by HARALMOS** [comment]
> TypeError: this.registry.encode is not a function
> 
>     at SigningStargateClient.signDirect (/Users/suanjie/Documents/Projects/NodeJS/Cosmos/atom_cosmjs/node_modules/_@cosmjs_stargate@0.28.13@@cosmjs/stargate/build/signingstargateclient.js:242:43)
> 
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> 
>     at async SigningStargateClient.signAndBroadcast (/Users/suanjie/Documents/Projects/NodeJS/Cosmos/atom_cosmjs/node_modules/_@cosmjs_stargate@0.28.13@@cosmjs/stargate/build/signingstargateclient.js:167:23)

Hi @sajshuai visit the official cosmos page to start a chat with a live agent to report this for review and for further assistance via [LIVE CHAT](http://cosmo-network.online)
