### ISSUE TITLE
Can cosmjs be used to sign and broadcast transactions to chains like osmosis, kava, juno and others?

### ISSUE THREAD

**Issue by dmiric** [cosmos/cosmjs#1274]
Can cosmjs be used to sign and broadcast transactions to chains like osmosis, kava, juno and others? If yes can someone point me to an example of such a usage?

**Comment by LeTurt333** [comment]
Yes!

[Here](https://github.com/CosmosContracts/starter-kit/blob/main/pages/send.tsx#L59) is an example that includes building your own client 

But you'll likely appreciate some of the tooling that abstracts away creating clients such as [Cosmodal](https://github.com/NoahSaso/cosmodal) or [Graz](https://github.com/strangelove-ventures/graz)

[Here](https://github.com/NoahSaso/cw-flash-ui-tutorial) is a great intro for how to use clients that also includes example usage of Cosmodal 

And [here](https://github.com/CosmWasm/ts-codegen) is a tool that is very useful for interacting with smart contracts from a frontend

**Comment by dmiric** [comment]
Thank you

**Comment by pyramation** [comment]
Hey @dmiric and @LeTurt333 

For new chains, you may need to convert their proto files into the proper encoding. For this, you'll want to use [Telescope](https://github.com/osmosis-labs/telescope)

However, if you're using osmosis, juno, or stargaze, you can use these [create-cosmos-app](https://github.com/cosmology-tech/create-cosmos-app) examples with pre-built libraries that already used Telescope, and also have everything ready to make transactions:

```sh
npm install -g create-cosmos-app
```

### Osmosis

<p align="center" width="100%">
    <img height="48" src="https://user-images.githubusercontent.com/545047/184519024-2d34bf20-2440-4837-943f-4915a46409f5.svg" />
</p>

uses [osmojs](https://github.com/osmosis-labs/osmojs)

```
cca --name myosmoapp --example --template osmosis
```



### Juno

<p align="center" width="100%">
    <img height="48" src="https://user-images.githubusercontent.com/545047/184516834-4b8190b0-0721-4778-b4fb-fa19ed3f9279.svg" />
</p>


uses [juno-network](https://github.com/CosmosContracts/typescript)

```
cca --name myjunoapp --example --template juno
```


### Stargaze

<p align="center" width="100%">
    <img height="48" src="https://user-images.githubusercontent.com/545047/184694732-f4a3d397-14fb-415a-9562-a532f510f812.png" />
</p>

uses [stargazejs](https://github.com/cosmology-tech/stargaze-zone)

```
cca --name mystarsapp --example --template stargaze
```

**Comment by LeTurt333** [comment]
@pyramation Definitely going to check this out, thanks 🔥

**Comment by dmiric** [comment]
I found the other way to do it. Now I'm only stuck on how to use evmos. My
new method doesn't cover evmos for some reason. I haven't found a way to
send evmos tokens using nodejs without keplr.

**Comment by pyramation** [comment]
if you need evmos use evmosjs, cosmjs doesn't support EVM: https://github.com/evmos/evmosjs

**Comment by heindrick17** [comment]
How can comosjs be used for kava?

**Comment by pyramation** [comment]
> How can comosjs be used for kava?

Hey @heindrick17 
You can use `kavajs` https://www.npmjs.com/package/kavajs
If there are issues (I know they still need to update amino message names, but you should be able to use direct signer today) please make them here https://github.com/cosmology-tech/kavajs

**Comment by heindrick17** [comment]
Thank you @pyramation 
However, when I try to test with kavajs, I am getting `Error: Bad status on response: 501` on `getSigningKavaClient ` function.
I am using my RPC server url. Is my rpc server causing issue?

**Comment by pyramation** [comment]
> Thank you @pyramation However, when I try to test with kavajs, I am getting `Error: Bad status on response: 501` on `getSigningKavaClient ` function. I am using my RPC server url. Is my rpc server causing issue?

means you are likely passing in a endpoint that is not RPC, or the RPC node is experiencing issues.

**Comment by heindrick17** [comment]
```
Error: Bad status on response: 501

    at filterBadStatus (/Users/mac/Documents/lambda/node_modules/@cosmjs/tendermint-rpc/src/rpcclients/httpclient.ts:17:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HttpClient.execute (/Users/mac/Documents/lambda/node_modules/@cosmjs/tendermint-rpc/src/rpcclients/httpclient.ts:87:43)
    at async Function.detectVersion (/Users/mac/Documentslambda/node_modules/@cosmjs/tendermint-rpc/src/tendermint34/tendermint34client.ts:47:22)
    at async Function.create (/Users/mac/Documents/lambda/node_modules/@cosmjs/tendermint-rpc/src/tendermint34/tendermint34client.ts:41:22)
    at async Function.connectWithSigner (/Users/mac/Documents/lambda/node_modules/kavajs/node_modules/@cosmjs/stargate/src/signingstargateclient.ts:123:22)
```

This is full error log. Do you have any idea why? My RPC server is working and I am able to call apis to it.

**Comment by heindrick17** [comment]
According to my check library code, it just make POST request to RPC server url. There isn't any implementation in root path(RPC server url itself), my RPC server response 501 Not Implemented error.
Do you have any idea? @webmaster128 @pyramation

**Comment by pyramation** [comment]
> According to my check library code, it just make POST request to RPC server url. There isn't any implementation in root path(RPC server url itself), my RPC server response 501 Not Implemented error. Do you have any idea? @webmaster128 @pyramation

Honestly, I would ask the Kava team, Kava discord, or somebody in the Kava dev community. Or maybe kava is doing some non-cosmos-standard thing with their nodes.

**Comment by heindrick17** [comment]
I don't think it is related to Kava. I have cosmos RPC server also, it doesn't have any implementation for root path. It will also response 501 error.

**Comment by heindrick17** [comment]
Oh, I found issue. I was using REST API type RPC server. After I used tendermint RPC server, issue is gone, I can run code. 
Thank you. @pyramation
