### ISSUE TITLE
Tendermint 37 TxResponse Decoding

### ISSUE THREAD

**Issue by blorgon1** [cosmos/cosmjs#1391]
When decoding a TxResponse using the Tendermint37Client (with a TM37 chain), this error is thrown:
```
Value must not be null

    at assertSet (node_modules/@cosmjs/tendermint-rpc/src/tendermint37/encodings.ts:17:11)
    at assertNotEmpty (node_modules/@cosmjs/tendermint-rpc/src/tendermint37/encodings.ts:115:3)
    at decodeTxProof (node_modules/@cosmjs/tendermint-rpc/src/tendermint37/adaptor/responses.ts:686:36)
    at may (node_modules/@cosmjs/tendermint-rpc/src/tendermint37/encodings.ts:127:62)
    at decodeTxResponse (node_modules/@cosmjs/tendermint-rpc/src/tendermint37/adaptor/responses.ts:715:15)
        at Array.map (<anonymous>)
    at decodeTxSearch (node_modules/@cosmjs/tendermint-rpc/src/tendermint37/adaptor/responses.ts:727:32)
    at decodeTxSearch (node_modules/@cosmjs/tendermint-rpc/src/tendermint37/adaptor/responses.ts:909:12)
    at Tendermint37Client.doCall (node_modules/@cosmjs/tendermint-rpc/src/tendermint37/tendermint37client.ts:342:12)
    at Tendermint37Client.txSearchAll (node_modules/@cosmjs/tendermint-rpc/src/tendermint37/tendermint37client.ts:281:20)
    at SigningStargateClient.txsQuery (node_modules/@cosmjs/stargate/src/stargateclient.ts:495:21)
    at SigningStargateClient.getTx (node_modules/@cosmjs/stargate/src/stargateclient.ts:381:21)
    at pollForTx (node_modules/@cosmjs/stargate/src/stargateclient.ts:458:22)
```

It seems that the proof response (at least for the `/tx_search` endpoint) is different, I've done some testing to identify the differences:
## TM37 no-proof
```
{
  "hash":"1C2B5E14718F09AAE96E06D9A138A0BB44F5C99D0666A09DBC8F552603110900",
  "height": 1102",
  ...
  "proof": {
    "root_hash":"",
    "data":null,
    "proof": {
      "total":"0",
      "index":"0",
      "leaf_hash":null,
      "aunts":null
    }
}
```

## TM37 with-proof
```
{
  "hash":"1C2B5E14718F09AAE96E06D9A138A0BB44F5C99D0666A09DBC8F552603110900",
  "height": 1102",
  ...
  "proof": {
    "total":"1",
    "index":"0",
    "leaf_hash":"GOKE4MbBlS2l2tJGlkBgyhCXpKh2/5yzpKruZrSbeyc=",
    "aunts":[]
  }
}
```

## TM34 no-proof
```
{
  "hash":"1C2B5E14718F09AAE96E06D9A138A0BB44F5C99D0666A09DBC8F552603110900",
  "height": 1102",
  ... (proof key is omitted)
}
```

## TM34 with-proof
```
{
  "hash":"1C2B5E14718F09AAE96E06D9A138A0BB44F5C99D0666A09DBC8F552603110900",
  "height": 1102",
  ...
  "proof": {
    "total": "10",
    "index": "0",
    "leaf_hash": "pwJs2FUkPCbPLbmnka10zSetH6u0mtDac5XLy3C+/L4=",
    "aunts": ["3jKHSNRjf81U45cI8rumBsOp530Oj4QigkrEpt8qGX4=", "FV0NRf9Fi9n+oKdAH9qrW2SZor1cJApr3K8N79K9Y8w=", "KTUfd4LBK+J1dVDUCyOD0pv4kyxMHs7lBJSef9U0g30=", "Q8a6aZ6culsJ2TGuJffdIpKsdngf2a+S8perAH6PDcQ="]
  }
}
```

**Comment by webmaster128** [comment]
Which Tendermint version is your backend using exactly?

We test this at Tendermint level in CI and always get an undefined (omitted) `proof` field for cometbft/cometbft:v0.37.0-rc3 and cometbft/cometbft:v0.37.0.

**Comment by webmaster128** [comment]
> Tendermint v0.35.5

We had a Tendermint 0.35 client here for some time. But given https://medium.com/the-interchain-foundation/discontinuing-tendermint-v0-35-a-postmortem-on-the-new-networking-layer-3696c811dabc we cannot put any resources into supporting other versions than 0.34 and 0.37.

**Comment by webmaster128** [comment]
Closing as out of scope since we don't support 0.35 backends
